
export const todosConstants = {
    FETCH_ALL_TODOS_REQUEST: 'FETCH_ALL_TODOS_REQUEST',
    FETCH_ALL_TODOS_SUCCESS: 'FETCH_ALL_TODOS_SUCCESS',
    FETCH_ALL_TODOS_FAILED: 'FETCH_ALL_TODOS_FAILED',

    CHANGE_ALL_TODOS_fILTER: 'CHANGE_ALL_TODOS_fILTER'
};
